- double-conversionConfig.cmake.in
Fedora's UsrMove causes issues with get_fileame_components returning odd paths.
Since we know the location of the file, just use it.  This also assumes changing CMake to cmake in the cmake file install location.  You might want to use another variable here instead.
> Use install paths in installed cmake files

- double-conversion/bignum.cc
I've gotten a number of reports on this in a project that vendors double-conversion. I've pasted an example of compiling with -Werror below. The fix is straight forward.
<pre>
==> jiffy (compile)
...
Compiling c_src/double-conversion/bignum.cc
c_src/double-conversion/bignum.cc: In member function ‘void double_conversion::Bignum::AssignDecimalString(double_conversion::Vector<const char>)’:
c_src/double-conversion/bignum.cc:101:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
void Bignum::AssignDecimalString(Vector<const char> value) {
^
cc1plus: all warnings being treated as errors
ERROR: c++ -c  -g -Wall -Werror -O3 -g -Wall -fPIC  -I/usr/lib/erlang/lib/erl_interface-3.7.20/include -I/usr/lib/erlang/erts-6.4/include …
> Fix compiler warning on GCC 5.1.0

- double-conversion/utils.h
Wrapped abort function in a noreturn function for MSC.
> fixed warning C4715 treated as error "not all control paths return a value"

- double-conversion/bignum-dtoa.h
- double-conversion/bignum.cc
- double-conversion/bignum.h
- double-conversion/cached-powers.cc
- double-conversion/diy-fp.cc
- double-conversion/diy-fp.h
- double-conversion/double-conversion.cc
- double-conversion/double-conversion.h
- double-conversion/fast-dtoa.h
- double-conversion/fixed-dtoa.h
- double-conversion/strtod.h
fixed inconsistent include paths
also, fixed compile error when library is included with the root to double-conversion source folder
> fixed inconsistent include paths

- CMakeLists.txt
- double-conversion/CMakeLists.txt
Not a big deal but with this change, one can just "git clone && add_subdirectory" to import double-conversion in another cmake solution.
Without it one need to add 
```cmake
target_include_directories(double-conversion PUBLIC $<BUILD_INTERFACE:${path_to_clone}>)
```
NB: I did not get the point of PROJECT_BINARY_DIR in removed cmake call
> set cmake include directories at target level

- double-conversion/CMakeLists.txt
prevent a "which is prefixed in the build directory" error
by providing a full path and setting only for BUILD_INTERFACE
to avoid conflict with cmake's install call below
see https://github.com/google/double-conversion/pull/19 post merge discussion
> fix cmake include directories at target level

- double-conversion/double-conversion.cc
DoubleToStringConverter::CreateDecimalRepresentation branch for ``decimal_point <= 0`` may require appending result_builder with zeroes when called from ToFixed, add corresponding commentary.
> actualize commentary

- WORKSPACE
This is necessary in order to build with Bazel.
Tested on Linux with the following command line:
$ bazel build //:all
For #11.
> add WORKSPACE file

- msvc/double-conversion.vcxproj
- msvc/double-conversion.vcxproj.filters
- msvc/double-conversion.vcxproj.user
- msvc/run_tests/run_tests.vcxproj
* Fix error C1128 for x86 debug builds.
The test\cctest\gay-precision.cc file will cause below error
for Visual Studio 2013.
`fatal error C1128: number of sections exceeded
object file format limit : compile with /bigobj`
* Use correct file paths.
The Visual Studio project files has outdated file paths.
* Remove user specific project file.
The *.vcxporj.user file should not be included in code repository.
> Update Visual Studio 2013 project files.

- BUILD
Tested on Linux with the following commands:
$ mkdir test-double-conversion
$ cd test-double-conversion
$ touch WORKSPACE
$ ln -s <path to double-conversion>
$ bazel test //double-conversion:all
> Add Bazel rules for running tests.

- BUILD
This should allow the following command line to work again:
$ bazel build //...
> fix Bazel's "includes" attribute error

- double-conversion/CMakeLists.txt
> Add fPIC flag on x86_64 if the compiler supports it.

- double-conversion/fixed-dtoa.cc
- test/cctest/test-fixed-dtoa.cc
When filling in fractional digits in a fixed representation we
might use all existing digits. When this happens, we can not look
at the next digit to see if we should round up.
Before this fix, we tried to shift by a negative amount to see if the
(non-existing) next bit was set to 1 (requiring the number to be rounded up).
Fixes #41.
> Avoid negative shift.

- double-conversion/strtod.cc
This is a simple change to cleanly handle the `#if` condition.
> Fix warning for code that will never be executed

- double-conversion/double-conversion.h
From looking at the code, it appears that functions such as those in fast_dtoa.cc write characters to the buffer relative to '0'.  That character is usually ASCII 0 (0x30, U+0030), but on certain platforms, such as those that use EBCDIC instead of ASCII, the literal `'0'` maps to a different char value.
The function `DoubleToAscii` should probably be named `DoubleToChars`, but good documentation should be sufficient without having to change the name of the function.
> Clarify output charset in DoubleToAscii documentation

- double-conversion/double-conversion.cc
- test/cctest/test-conversions.cc
With ALLOW_JUNK enabled, `processed_characters_count` was previously including malformed exponent suffixes. Converting "123e-", for example, would set `*processed_characters_count` to 5.
> Processed length should include no trailing junk

- double-conversion/utils.h
More info about ARC architecture is here: [1] & [2].
We need ARC supported here for many things like:
- ICU (see [3])
- Qt5 etc
[1] https://www.synopsys.com/designware-ip/processor-solutions/arc-processors.html
[2] https://en.wikipedia.org/wiki/ARC_(processor)
[3] https://unicode-org.atlassian.net/browse/ICU-20155
Fixes #81
> Add support of ARC architecture

- CMakeLists.txt
64-bit libraries should be installed in /usr/lib64, not in /usr/lib/
Make the destination lib dir configurable.
Commit e13e72e17692f5dc0036460d734c637b563f3ac7 removed
include(GNUInstallDirs) and ${CMAKE_INSTALL_LIBDIR} which broke
installing on 64-bit systems.
Signed-off-by: Jason Zaman <jason@perfinion.com>
> CMake: install to correct lib dir

- double-conversion/bignum.cc
- double-conversion/double-conversion.cc
- double-conversion/utils.h
(With the usual additional brackets to prevent interference with macros named min/max on Windows.)
> Use standard min/max.

- double-conversion/bignum.cc
- double-conversion/bignum.h
Bignum consists of an array of 128 unsigned 32bit integers and some additional information. Previously the additional information was after the array, thereby requiring two cachelines to be loaded even when manipulating very small represented numbers. This PR reverses the order, placing the additional information at the beginning, so small Bignums can touch only one cacheline. It also removes the redundant `Vector<Chunk>`, thereby reducing the size of the additional information by 16 bytes (on a normal 64bit machine with 64bit-aligned pointers), making room for another 4 Bigits in the first cacheline.
> Optimise Bignum layout.

- AUTHORS
- Changelog
- double-conversion/double-to-string.cc
- double-conversion/double-to-string.h
- test/cctest/test-conversions.cc
Prefix 0 is added when call golang fmt.Sprint() to convert double to shortest string
For example: 0.00001 is convert to 1e-05, but not 1e-5
In some situations, I want to convert double to shortest string in "golang format", so a "min exponent width option" will be useful
> Add min exponent width option in double-to-string shortest conversion

- double-conversion/utils.h
Summary:
Emscripten is already included, adding wasm32 the same way when
building with "plain" clang wasm32 (without emscripten)
Test Plan:
make
test/cctest/cctest --list | tr -d '<' | xargs test/cctest/cctest
Reviewers:
Subscribers:
Tasks:
Tags:
> Add wasm32 as supported platform

- test/cctest/test-conversions.cc
- test/cctest/test-diy-fp.cc
- test/cctest/test-fast-dtoa.cc
- test/cctest/test-ieee.cc
- test/cctest/test-strtod.cc
Some files in cctest had a 1-line copyright that doesn't list the
license. This copies the project license to those files, preserving the
date.
> Add full license to test .cc files missing it.

- double-conversion/strtod.cc
When DOUBLE_CONVERSION_CORRECT_DOUBLE_OPERATIONS is not defined
there is a build error when -Wall -Werror enabled because
kMaxExactDoubleIntegerDecimalDigits, exact_powers_of_ten and
kExactPowersOfTenSize are used only in else branch of this define
(when it's defined).
Fixes https://github.com/google/double-conversion/issues/122
> Fix strtod.cc undefined constants

- double-conversion/string-to-double.cc
- double-conversion/utils.h
Simplifies code by removing two asserts
Optimize code with -ftrivial-auto-var-init=pattern by avoiding initialization when buffer is not used
Related bug https://bugs.chromium.org/p/chromium/issues/detail?id=977230
> Move buffer and buffer_pos down

- msvc/double-conversion.vcxproj
- msvc/double-conversion.vcxproj.filters
- msvc/run_tests/run_tests.vcxproj
Hello!
I was trying to get the project to build with MSVC using Visual Studio, but it looks like some files have been moved around and the existing `*.vcxproj` files are a bit stale. It appears as though the change in #104 renamed/moved files around, but the VS projects weren't updated.
This change fixes the existing `*.vcxproj` files in order to unblock building/compiling with MSVC via Visual Studio.
Thanks!
> Fix broken MSVC builds.

- .gitignore
- BUILD
The pull request https://github.com/google/double-conversion/pull/104 didn't update Bazel build files after reorganizing source code. This should update the Bazel build files to allow building with Bazel successfully.
> Fixes bazel build for downstream projects.

- test/cctest/CMakeLists.txt
On MSVC with Visual Studio 2017 and 2019, I get errors when building the tests because the number of sections in the object file is exceeded. I found that MSVC requires the compiler flag `/bigobj` to switch to a different storage format that allows a much larger number of sections.
As far as I know there is no downside to using this flag. Also, this PR introduces the change only for tests. Therefore this PR should not lead to any negative consequences for any users.
> Add /bigobj for MSVC tests

- CMakeLists.txt
Currently the cmake based build creates shared libraries on MSVC that do not export any symbols. The shared library therefore has no import library (missing `double-conversion.lib`) and the shared library is basically 'empty' and can not be used for linking.
The clean solution on MSVC is to use the `declspec(dllexport)` and `declspec(dllexport)` keywords to correctly export symbols as required. But cmake offers a useful workaround that comes with virtually no downsides: The cmake setting WINDOWS_EXPORT_ALL_SYMBOLS (see https://cmake.org/cmake/help/latest/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html) can be used to export all symbols from a library. This is not as specific as the aforementioned solution based on `declspec(dllexport)` and `declspec(dllexport)`, but it allows a correct build and …
> CMakeLists.txt: Export all symbols for MSVC shared library (DLL) build

- double-conversion/bignum-dtoa.cc
Google's double conversion repo is used by ICU, where we have noticed several typos and misspellings across the repo. I am fixing those, but since double-conversion gets updated sometimes, I may as well fix them here as well :) So everyone can have the correct thing :)
I will probably open more of these PR's while fixing typos and misspellings on ICU.
Thanks!
> Fix typos on files

- double-conversion/double-to-string.cc
- double-conversion/double-to-string.h
- test/cctest/test-conversions.cc
With this, %g can be emulated with:
```
DoubleToStringConverter cvt(
UNIQUE_ZERO | NO_TRAILING_ZERO | EMIT_POSITIVE_EXPONENT_SIGN,
"inf", "nan", 'e', 0, 0, 4, 0, 2)
```
> Add a flag to make precision mode like printf's %g

- double-conversion/strtod.cc
It's only used in an assertion, hence it's unused when assertions are off.
> Avoid unused function warning for AssertTrimmedDigits()

- double-conversion/double-to-string.h
- test/cctest/test-conversions.cc
> Allow 100 decimal digits for 'toFixed'.

- double-conversion/string-to-double.cc
- double-conversion/strtod.cc
- double-conversion/strtod.h
- test/cctest/test-strtod.cc
We know the buffer contains no leading zeros and less than kMaxSignificantDecimalDigits, so we only need to trim trailing zeros and can then call Strto*Trimmed, which is quite a bit faster.
> Call StrtodTrimmed/StrtofTrimmed from StringToDoubleConverter::StringToIeee.

- double-conversion/string-to-double.cc
- double-conversion/string-to-double.h
- test/cctest/test-conversions.cc
Allowed users to write generic code more easily, like this (when `T` is
either `float` or `double`):
converter.StringTo<T>(buffer, length, &processed);
Included a unit test, `TEST(StringToTemplate)`.
Fixes issue https://github.com/google/double-conversion/issues/157
With help from Florian Loitsch (@floitsch)
> Add `StringToDoubleConverter::StringTo<T>` member function templates

- double-conversion/utils.h
This PR is to add support of Synopsys ARC64 architecture
> double-conversion/utils.h: Add support of Synopsys ARC64 architecture

- double-conversion/ieee.h
Please refer to https://en.wikipedia.org/wiki/NaN, the MIPS* and PA-RISC
(also known as HPPA) architectures regard the "is_quiet/is_signaling" bit
the reversed way compared to other architectures.
This patch fixes https://github.com/google/double-conversion/issues/171
> ieee.h: Fix QuietNan check for MIPS* and PA-RISC architectures.

- double-conversion/utils.h
This came up while enabling more warnings downstream in Chromium.
> Add a cast to silence a signedness conversion warning.

- double-conversion/double-to-string.cc
- double-conversion/double-to-string.h
- test/cctest/test-conversions.cc
~~This implements an improvement in how the `EMIT_TRAILING_DECIMAL_POINT` and `EMIT_TRAILING_ZERO_AFTER_POINT` flags affect~~  This adds new flags `EMIT_TRAILING_DECIMAL_POINT_IN_EXPONENTIAL` and `EMIT_TRAILING_ZERO_AFTER_POINT_IN_EXPONENTIAL` to control the trailing decimal and zero in conversion to scientific notation when the input number has exactly one significant digit.
These flags control the behavior of `ToShortest()` and `ToPrecision(, 1)` which currently do not respect the existing flags `EMIT_TRAILING_DECIMAL_POINT` and `EMIT_TRAILING_ZERO_AFTER_POINT` in this situation. `ToExponential()` OTOH _does_ respect the existing flags in this situation, and its behavior is unaffected by these new flags.
For example: when both of the new flags are activated, `ToShortest(0.00001)` and …
> Add flags to control trailing decimal and zero in exponent form when input has one significant digit

- .github/workflows/ci.yml
- .github/workflows/scons.yml
#197 
Hash pin GitHub Owned Workflows: although they are more trustful than the overall github actions it is important to notice that they are still open source projects.
Let me know what you think.
PS: this is just an extra precaution, the workflow is already safe enough following minimal permissions on workflow. The hash pin will only ensure that no "malicious" version will be running instead of the original and trustful one.
> Hash pin Github workflows

- CMakeLists.txt
- msvc/double-conversion.vcxproj
On Windows, the _ITERATOR_DEBUG_LEVEL flag is not set for Debug builds.  This causes mismatch errors when attempting to build consuming codebases where this flag *is* set.
I have personally run in to this issue when attempting to build Qt 5.15.2.
My change appends `_ITERATOR_DEBUG_LEVEL=2` and `_DEBUG` to the `CMAKE_CXX_FLAGS_DEBUG` variable, allowing the values to appear in the preprocessor list in the generated .vcxproj file (debug only).  The flags have also been manually added to the existing .vcxproj file, in the `msvc/` directory.
> Add _ITERATOR_DEBUG_LEVEL=2 and _DEBUG defines

- MODULE.bazel
This adds support for building this module with bazel's bzlmod dependency management enabled.
> Add bzlmod MODULE.bazel file

- .github/dependabot.yml
- .github/workflows/scorecard.yml
- README.md
Closes #204 
Hi, here is the openssf scorecard configuration with its badge. It is also possible to provide a fine-grained PAT for the action to also verify Branch Protection rules.
Let me know if you want to reduce the comments or keep it extensively commented.
Thanks!
> Configure OpenSSF Scorecard

- MODULE.bazel
- README.md
This pull request is to upstream the change in the Bazel registry: https://github.com/bazelbuild/bazel-central-registry/blob/072b50524565ef21da258d7d9eaab057c5a8db33/modules/double-conversion/3.3.0/MODULE.bazel
As a general rule, `compatibility_level` is set to the major version number.
> Update MODULE.bazel and README.md.

- BUILD
- MODULE.bazel
In general, `cc_library` and `cc_test` do not need an explicit load. By removing it, we can remove the explicit dependency to `rules_cc` in `MODULE.bazel`. This makes the dependency management easier. Nothing should be broken by this change.
> Remove the explicit dependency on rules_cc.

- CMakeLists.txt
- test/cctest/cctest.h
Two changes:
1. Add `#include <cinttypes>` to `test/cctest/cctest.h`. Without it, on Linux systems, the following error occurs:
```
note: 'PRId64' is defined in header '<cinttypes>'; did you forget to '#include <cinttypes>'?
```
and similarly for `PRIu64` macro. 
2. `double-conversion/bignum-dtoa.h` added as a required header in `CMakeLists.txt`.
`double-conversion/bignum-dtoa.cc` is added to the library which references this header.
> Add missing headers

- CMakeLists.txt
CMake >= 4.0.0-rc1 removed compatibility with versions < 3.5 and errors out with such versions passed to cmake_minimum_required(). 3.5.0 has been released 9 years ago, so I'd assume it's available almost everywhere.
> CMake: Raised required version to 3.5

- double-conversion/double-to-string.cc
This shouldn't have any effect since the variable was only uninitialized if 0 digits were requested. Still good practice.
Fixes #243.
> Always initialize decimal-point variable.

- double-conversion/double-to-string.h
> Explain that ToShortest might not be the shortest.

- CMakeLists.txt
This allows consuming the library in a `add_subdirectory` use-case as-if it was installed
> Add alias double-conversion::double-conversion

- CMakeLists.txt
- msvc/double-conversion.vcxproj
This reverts commit dfa08c464fe164e5c70e3f080e30cc977fbb0aa9.
The original change is invalid. `_ITERATOR_DEBUG_LEVEL=2` is the default value in debug builds. And now it's impossible to override it because it's *appended* to `CMAKE_CXX_FLAGS_DEBUG`.
I suspect that the original problem was that release double-conversion library was used in debug builds of Qt. This is not something that should be fixed in double-conversion.
> Revert "Add _ITERATOR_DEBUG_LEVEL=2 and _DEBUG defines (#202)"
